name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  name: Run Tests
  test:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Cache pre-commit
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ runner.os }}-

      - name: Install python dependencies
        run: uv sync --frozen --no-install-project

      - name: Run pre-commit
        if: success() || failure()
        run: |
          uv run pre-commit run --all-files
          git diff --exit-code

      - name: Run detect-secrets
        if: success() || failure()
        run: git ls-files | xargs uv run detect-secrets-hook --baseline .secrets.baseline

      - name: Run Ruff format & lint
        if: success() || failure()
        run: |
          uv run ruff check --fix --exit-zero .
          uv run ruff check --fix --extend-ignore=PLR2004 .
          uv run ruff format .
          git diff --exit-code

      - name: Run dprint
        if: success() || failure()
        run: |
          git ls-files | grep -v '{{_copier_conf.answers_file}}.jinja' | xargs uv run dprint fmt
          git diff --exit-code

      - name: Run mypy
        if: success() || failure()
        run: uv run mypy .

      - name: Run pytest
        if: success() || failure()
        run: uv run pytest
