name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Cache dprint plugins
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: ~/.cache/dprint
          key: dprint-${{ runner.os }}-${{ hashFiles('dprint.json') }}
          restore-keys: |
            dprint-${{ runner.os }}-

      - name: Install python dependencies
        run: uv sync --frozen --group github-workflows --no-install-project

      - name: Run pre-commit
        if: success() || failure()
        run: |
          echo "### pre-commit results" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`text" >> $GITHUB_STEP_SUMMARY

          set +e
          uv run lefthook run pre-commit --all-files 2>&1 | tee -a $GITHUB_STEP_SUMMARY
          EXIT_CODE=${PIPESTATUS[0]}
          set -e

          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          exit $EXIT_CODE

      - name: Run pytest
        if: success() || failure()
        run: uv run pytest --junitxml=results.xml || [[ $? -eq 5 ]]

      - name: Pytest Test Summary
        uses: test-summary/action@37b508cfee6d4d080eedd00b5bb240a6a784a6a5 # v2
        with:
          paths: results.xml
